"use client";

import type { ChangeEvent } from "react";
import { Download, Eye, FileText, FileUp, ShieldAlert, Trash2 } from "lucide-react";
import type { CaseFact, DocumentItem } from "@/lib/api";
import { EntityCode, ReasoningStatusBadge } from "@/components/ui/ReasoningUI";
import { EmptyState, PanelHeading, StatusBadge } from "./shared";

function formatFileSize(size: number | null) { if (!size) return "未知大小"; if (size < 1024) return `${size} B`; if (size < 1024 * 1024) return `${(size / 1024).toFixed(1)} KB`; return `${(size / 1024 / 1024).toFixed(1)} MB`; }
const documentStatusLabel: Record<string, string> = { uploaded: "已上传", parsing: "解析中", parsed: "已解析", analyzing: "分析中", ready: "已完成", parse_failed: "解析失败", analysis_failed: "分析失败" };

export function MaterialsPanel({ documents, facts, busy, onUpload, onDownload, onDelete }: { documents: DocumentItem[]; facts: CaseFact[]; busy: string; onUpload: (event: ChangeEvent<HTMLInputElement>) => void; onDownload: (item: DocumentItem) => void; onDelete: (item: DocumentItem) => void }) {
  return <section className="space-y-5"><PanelHeading title="材料与脱敏" description="原始材料进入事实提取流程；脱敏能力将在后续版本接入。" action={<label className="button-secondary cursor-pointer"><FileUp size={16} />{busy === "upload" ? "正在上传" : "上传材料"}<input className="hidden" type="file" accept=".txt,.pdf,.docx" onChange={onUpload} /></label>} /><div className="feedback-state border-slate-200 bg-slate-50"><ShieldAlert size={17} className="text-slate-500" /><span><strong>材料脱敏尚未接入。</strong> 当前事实提取仍使用原始解析文本，请勿上传不应进入演示环境的敏感材料。</span><ReasoningStatusBadge status="unavailable" /></div>{!documents.length ? <EmptyState title="暂无案件材料" description="上传 PDF、DOCX 或 TXT 后，文件及解析状态会显示在这里。" /> : <div className="space-y-3">{documents.map((item) => { const legacy = item.storage_provider === "legacy_local"; const sourceName = item.original_filename || item.filename; const citations = facts.filter((fact) => fact.source_document === sourceName || fact.source_document === item.filename).length; const status = documentStatusLabel[item.processing_status] || (item.raw_text ? "已完成" : "待处理"); return <article key={item.id} className="reasoning-card"><div className="flex flex-wrap items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-slate-100 text-court"><FileText size={19} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><EntityCode kind="document" id={item.id} /><h3 className="min-w-0 truncate font-semibold text-ink">{sourceName}</h3><StatusBadge status={status} /></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span>{item.file_type?.toUpperCase() || "文件"}</span><span>{formatFileSize(item.file_size)}</span><span>事实引用 {citations}</span><span>{new Date(item.uploaded_at).toLocaleString("zh-CN")}</span></div>{legacy && <p className="mt-3 text-xs text-amber-700">旧材料：原始文件可能已不可用，已保留解析文本。</p>}</div><div className="flex gap-2"><button className="button-secondary" type="button" title="下载" disabled={Boolean(busy) || legacy} onClick={() => onDownload(item)}><Download size={16} /></button><button className="button-secondary" type="button" title="删除" disabled={Boolean(busy)} onClick={() => onDelete(item)}><Trash2 size={16} /></button></div></div><details className="mt-4 border-t border-line pt-3"><summary className="flex cursor-pointer items-center gap-2 text-sm font-medium text-court"><Eye size={15} />查看文本预览</summary><p className="mt-3 max-h-64 overflow-y-auto whitespace-pre-wrap rounded-md bg-slate-50 p-3 text-sm leading-7 text-slate-600">{item.raw_text || item.extraction_error || "该材料尚无可用解析文本。"}</p></details></article>; })}</div>}</section>;
}
